### ISSUE TITLE
Disable Hochzeit

### ISSUE THREAD

**Issue by mkre** [mkre/Schafkopf#1]
Hochzeit is no part of our rule set, so we should disable this option.

**Comment by PeterPablo** [comment]
Hiding Hochzeit based on a settings flag would allow others to still use this game style if desired, while still benefiting from all the other code improvements.

**Comment by mkre** [comment]
@PeterPablo Thanks for your comment. I was following the [YAGNI principle](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) here. This fork is already tailored to our club's rules, so I preferred to simplify the code and get rid of rules we are never going to need anyway. However, given that there seems to be some demand to get Hochzeit back optionally, we can just revert the commit and modify it to keep Hochzeit as an optional rule.

**Comment by dermig** [comment]
Hochzeit is optional
