### ISSUE TITLE
Refusal/play announcements changing after each player

### ISSUE THREAD

**Issue by mkre** [mkre/Schafkopf#8]
The concrete refusal/play announcement ("weg", "fuera", "dat") currently changes after each player's announcement. It should be sticky as long as announcements are made.

**Comment by PeterPablo** [comment]
Code improvement suggestion: Taking a value from a tuple could be de-duplicated into a small helper function which takes an array as input and returns one of its members as output.

**Comment by mkre** [comment]
Thanks @PeterPablo. I have refactored the implementation in [1681069](https://github.com/mkre/Schafkopf/commit/16810691b25560b782d097210fcf8cb6aed36d89).

**Comment by dermig** [comment]
@PeterPablo should be solved - please check / conduct V&V and re-open issue if necessary.
